data:
  img_size: 448
  dataset: custom
  batch_size: 14
  resize: 600
  color: 0.4
  data_root: 'E:\Thesis\Datasets\split_70_30'
model:
  baseline_model: False
  drop_path: 0.
  label_smooth: 0.
parameters:
  vote_perhead: 24
  loss_alpha: 0.4
  total_num: 126
  fix: True
  dsm: True
  cam: True
  assess: False
train:
  lr: 0.0025
  epochs: 40
#  freeze_backbone: True
#misc:
#  throughput: True
#  eval_mode: True
